# Site settings
title: Offensive Hub - Offensive penetration testing tools
description: We make modern and up-to-date penetration testing software. Our software all have GUI. We are Open Source lovers.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Offensive Hub
user_description: We make modern and up-to-date penetration testing software. Our software all have GUI. We are Open Source lovers.
user_title: Offensive penetration testing tools
email: offensive-hub@protonmail.com
twitter_username: Offensive_Hub
github_username:  offensive-hub
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
